### ISSUE TITLE
why the example result is inconsistent with the paper

### ISSUE THREAD

**Issue by yvonnefff** [MasterAI-EAM/Darwin#5]
![F7B51BBD-0EA3-47A7-BA12-E3D37E079B24](https://github.com/MasterAI-EAM/Darwin/assets/76763339/12c3a5c5-30bf-4ad8-b719-24e04393491b)
example.ipynb result is 2.26。
but in paper，the result is 2.87
![5B310497-F509-462D-BB4F-FA9CC502DB11](https://github.com/MasterAI-EAM/Darwin/assets/76763339/c5b30471-b678-4bf3-ba44-d7eece27d5e4)

**Comment by 0xTong** [comment]
Hi @yvonnefff thanks for your feedback. @yuweiwan  Could you recheck that? might be the temperature setting problem.

**Comment by yuweiwan** [comment]
Thank you for your question. Firstly, our data format follows the stanford_alpaca format (https://github.com/tatsu-lab/stanford_alpaca/blob/main/alpaca_data.json). The examples presented in our paper represent instruction data, with the output being the correct answers, rather than the model's outputs. We will clarify this point further in the revised version of the paper. Secondly, due to the nature of generative models, for a fixed input question, the inference output may not necessarily be the same each time.
